### ISSUE TITLE
Color theme

### ISSUE THREAD

**Issue by grigorii-horos** [jackharrisonsherlock/common#10]
Can you show your colors in terminal emulator?

**Comment by jackharrisonsherlock** [comment]
Hey, i'm now using an updated version of this prompt so not using the same colours as the screenshot in the readme. 

The colours are customisable, just edit the common.zsh-theme file and change the below to suit your style: 

```# Colors
COMMON_COLORS_HOST_ME=green
COMMON_COLORS_HOST_AWS_VAULT=yellow
COMMON_COLORS_CURRENT_DIR=blue
COMMON_COLORS_RETURN_STATUS_TRUE=yellow
COMMON_COLORS_RETURN_STATUS_FALSE=red
COMMON_COLORS_GIT_STATUS_DEFAULT=green
COMMON_COLORS_GIT_STATUS_STAGED=red
COMMON_COLORS_GIT_STATUS_UNSTAGED=yellow
COMMON_COLORS_GIT_PROMPT_SHA=green
COMMON_COLORS_BG_JOBS=yellow

**Comment by grigorii-horos** [comment]
@jackharrisonsherlock Sorry, but I ask about colors in terminal emulator.

**Comment by jwalsh2me** [comment]
@jackharrisonsherlock I think he means the Terminal Theme you used in the screenshot.

**Comment by jackharrisonsherlock** [comment]
@jwalsh2me Thanks!

@grigorii-horos It's [Atom one dark](https://github.com/ggamel/hyper-one-dark) theme with some slight tweaks.
