### ISSUE TITLE
Unable to use "%" as the prompt symbol

### ISSUE THREAD

**Issue by joeleisner** [jackharrisonsherlock/common#5]
Hey, @jackharrisonsherlock !

Now that there's color variables in this prompt, I was attempting to set it up on my local machine; My idea is that my prompt would change color/look based on whether I was on my regular user account or logged in as root.

One of things I planned to differentiate the two is to use the "%" symbol for my regular user, and "#" for my root user. While the "#" works, using "%" actually shows "%f" in the terminal. I'm assuming this has to do with the "%f" at the end of the `common_return_status` function, but I'm not entirely sure (hence why I didn't make a pull request).

Things to do to reproduce - Set the following global variable after the ZSH prompt is loaded:

```shell
COMMON_PROMPT_SYMBOL="%"
```

Let me know what you think or if you need more information!

**Comment by jackharrisonsherlock** [comment]
Hey @joeleisner, the %F and %f are the start/stop effects to change the foreground colour of the symbol. 

If you want to set the prompt to %, you could try changing the `common_return_status` to 

```
common_return_status() {
  echo -n "%(?.%F{$COMMON_COLORS_RETURN_STATUS_TRUE}.%F{$COMMON_COLORS_RETURN_STATUS_FALSE})$COMMON_PROMPT_SYMBOL%$reset_color%} "
}
```

Just gave it a shot and seems to be what you are after?
![  2019-07-25 at 1 29 19 pm](https://user-images.githubusercontent.com/23329559/61839077-4b417880-aee0-11e9-83ef-d868c7931a95.png)

**Comment by joeleisner** [comment]
Hey, @jackharrisonsherlock !

That definitely seems to work. Is there anything neutral to both your default character and characters such as "%" that could be merged into your project? If so, I'd be happy to open up a pull-request, however I'm not familiar with these special characters.

**Comment by jackharrisonsherlock** [comment]
Sorry @joeleisner, must have missed this reply!

Thanks for the offer but I'd like to keep the code clean with the current setup of changing the prompt using the variable.
