### ISSUE TITLE
Customising colors

### ISSUE THREAD

**Issue by madhavtummala** [jackharrisonsherlock/common#6]
Is there any easy way to customise the color for each segment of the prompt?   
Currently only `red, yellow, green, blue` are available as common colors.  
I tried replacing them with ascii codes of other colors, but did not succeed.

**Comment by jackharrisonsherlock** [comment]
If you are using oh-my-zsh it uses spectrum https://github.com/sykora/etc/blob/master/zsh/functions/spectrum/

So you can change the individual colours with something like this:

```
COMMON_COLORS_HOST_ME=201
COMMON_COLORS_HOST_AWS_VAULT=196
```

Type this in your terminal to see the colour codes:

```
for i in {0..255} ; do
    printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
    if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 6 == 0 )); then
        printf "\n";
    fi
done
```
