### ISSUE TITLE
Seems like `antibody bundle` doesn't work.

### ISSUE THREAD

**Issue by ob1dev** [jackharrisonsherlock/common#9]
Seems like `antibody bundle` doesn't work. I get this after adding it:

```
# ~/.zshrc
antibody bundle jackharrisonsherlock/common
```

<img width="931" alt="Screen Shot 2020-08-09 at 7 50 21 PM" src="https://user-images.githubusercontent.com/2487951/89748736-91309680-da79-11ea-9206-aa6f8029687f.png">

**Comment by jackharrisonsherlock** [comment]
Hey Oleg, thanks for raising! I don't actually use antibody myself, does the standard oh my zsh installation method work for you?

**Comment by ob1dev** [comment]
Yes, Oh My Zsh works.

Thanks for creating this prompt. It's awesome!

**Comment by jackharrisonsherlock** [comment]
I'll try replicate the antibody issue and see if I can fix it.

Thanks for the kind words!
